M48
; DRILL file {KiCad (6.0.1)} date Tue Mar 29 16:10:15 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-29T16:10:15-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.165Y-1.745
X2.165Y-3.56
X3.705Y-1.745
X3.705Y-3.56
T0
M30
