M48
; DRILL file {KiCad (6.0.1)} date Tue Mar  8 00:56:29 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-08T00:56:29-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X7.61Y-3.39
X7.61Y-5.585
X10.11Y-3.39
X10.11Y-5.585
T0
M30
